stripe_api_key: sk_test_51LzVKrEjCVMHWZtIOBg0nSEE2BefJmiF98nXKkf7GZlZ2gZC3Y2bDfbEewkOpdlWEGcJC7p1xSGn4ubFdSqazQXn00g7lj0S2z
stripe_publishable_key: pk_test_51LzVKrEjCVMHWZtI6eK6uXRgJ057Y4JPBErB1QSKFpOPeN9u5r4vlMGofMdgbXAgpVgfqyaFWGMD8WaUro7O2WGF00mz7Lq0oV

production:
  stripe_api_key: sk_test_51LzVKrEjCVMHWZtIOBg0nSEE2BefJmiF98nXKkf7GZlZ2gZC3Y2bDfbEewkOpdlWEGcJC7p1xSGn4ubFdSqazQXn00g7lj0S2z
  stripe_publishable_key: pk_test_51LzVKrEjCVMHWZtI6eK6uXRgJ057Y4JPBErB1QSKFpOPeN9u5r4vlMGofMdgbXAgpVgfqyaFWGMD8WaUro7O2WGF00mz7Lq0oV